# start off by defining the schema version
version: '3.9'
#define the list of services (or containers) we want to run as part of our application
services:
  prod:
    container_name: backend_api
    image: backend-dockerized
    build:
      context: .
      target: production
      dockerfile: ./Dockerfile
    command: npm run start:prod
    ports:
      - 3000:3000
      - 8080:8080
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

networks:
  nesjs-network:
